#!/bin/bash

# set the root directory as a "files"
cd files

# files 디렉토리 안에 있는 모든 파일에 대해 반복합니다.
for file in *
do
  # extract the first letter of the file name
  first_letter=$(echo $file | cut -c 1 | tr '[:upper:]' '[:lower:]')

  # move the file
  mv $file ../$first_letter/
done
